title: Press Kit
description: A press kit kit!

collections:
  products:
    output: true
    permalink: /:name

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "products"
    values:
      layout: "product"
  - scope:
      path: "assets/images/header.*"
    values:
      header: true
  - scope:
      path: "assets/images"
    values:
      image: true
  - scope:
        path: "assets/images/company"
    values:
      company-image: true
  - scope:
      path: "assets/images/*/*.png"
    values:
      png: true
  - scope:
      path: "assets/images/*/*.jpg"
    values:
      jpg: true
      jpeg: true
  - scope:
      path: "assets/images/*/*.jpeg"
    values:
      jpg: true
      jpeg: true
  - scope:
      path: "assets/images/*/*.gif"
    values:
      gif: true
  - scope:
      path: "assets/images/*/*.webp"
    values:
      webp: true
  - scope:
      path: "assets/images/*/*.ico"
    values:
      ico: true
  - scope:
      path: "assets/images/*/*.svg"
    values:
      svg: true
  - scope:
      path: "assets/images/*/favicon.*"
    values:
      favicon: true
  - scope:
      path: "assets/images/*/*header*.*"
    values:
      header: true
  - scope:
      path: "assets/images/*/*logo*.*"
    values:
      logo: true
  - scope:
      path: "assets/images/*/*screenshot*.*"
    values:
      screenshot: true
  - scope:
      path: "assets/images/*/*wallpaper*.*"
    values:
      wallpaper: true

strict_front_matter: true

sass:
    sass_dir: _sass
    style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - .vscode
  - .idea
  - .gitignore
  - README.md
  - LICENSE
  - _config.yml
